//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaFinanciera.ServicioPublicoOnline {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoEstadoCliente", Namespace="http://schemas.datacontract.org/2004/07/SGE.Service.Contracts.Data")]
    [System.SerializableAttribute()]
    public partial class ResultadoEstadoCliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadCreditosActivosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ConsultaValidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TieneDeudasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadCreditosActivos {
            get {
                return this.CantidadCreditosActivosField;
            }
            set {
                if ((this.CantidadCreditosActivosField.Equals(value) != true)) {
                    this.CantidadCreditosActivosField = value;
                    this.RaisePropertyChanged("CantidadCreditosActivos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ConsultaValida {
            get {
                return this.ConsultaValidaField;
            }
            set {
                if ((this.ConsultaValidaField.Equals(value) != true)) {
                    this.ConsultaValidaField = value;
                    this.RaisePropertyChanged("ConsultaValida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TieneDeudas {
            get {
                return this.TieneDeudasField;
            }
            set {
                if ((this.TieneDeudasField.Equals(value) != true)) {
                    this.TieneDeudasField = value;
                    this.RaisePropertyChanged("TieneDeudas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorServicio", Namespace="http://schemas.datacontract.org/2004/07/SGE.Service.Contracts.Faults")]
    [System.SerializableAttribute()]
    public partial class ErrorServicio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError {
            get {
                return this.MensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorField, value) != true)) {
                    this.MensajeErrorField = value;
                    this.RaisePropertyChanged("MensajeError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoOperacion", Namespace="http://schemas.datacontract.org/2004/07/SGE.Service.Contracts.Data")]
    [System.SerializableAttribute()]
    public partial class ResultadoOperacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OperacionValidaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OperacionValida {
            get {
                return this.OperacionValidaField;
            }
            set {
                if ((this.OperacionValidaField.Equals(value) != true)) {
                    this.OperacionValidaField = value;
                    this.RaisePropertyChanged("OperacionValida");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ISTP1.Service.Contracts.Service", ConfigurationName="ServicioPublicoOnline.IServicioPublicoCredito")]
    public interface IServicioPublicoCredito {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ISTP1.Service.Contracts.Service/IServicioPublicoCredito/ObtenerEstadoClien" +
            "te", ReplyAction="http://ISTP1.Service.Contracts.Service/IServicioPublicoCredito/ObtenerEstadoClien" +
            "teResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LaFinanciera.ServicioPublicoOnline.ErrorServicio), Action="http://ISTP1.Service.Contracts.Service/IServicioPublicoCredito/ObtenerEstadoClien" +
            "teErrorServicioFault", Name="ErrorServicio", Namespace="http://schemas.datacontract.org/2004/07/SGE.Service.Contracts.Faults")]
        LaFinanciera.ServicioPublicoOnline.ResultadoEstadoCliente ObtenerEstadoCliente(string codigoFinanciera, int dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ISTP1.Service.Contracts.Service/IServicioPublicoCredito/ObtenerEstadoClien" +
            "te", ReplyAction="http://ISTP1.Service.Contracts.Service/IServicioPublicoCredito/ObtenerEstadoClien" +
            "teResponse")]
        System.Threading.Tasks.Task<LaFinanciera.ServicioPublicoOnline.ResultadoEstadoCliente> ObtenerEstadoClienteAsync(string codigoFinanciera, int dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ISTP1.Service.Contracts.Service/IServicioPublicoCredito/InformarCreditoOto" +
            "rgado", ReplyAction="http://ISTP1.Service.Contracts.Service/IServicioPublicoCredito/InformarCreditoOto" +
            "rgadoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LaFinanciera.ServicioPublicoOnline.ErrorServicio), Action="http://ISTP1.Service.Contracts.Service/IServicioPublicoCredito/InformarCreditoOto" +
            "rgadoErrorServicioFault", Name="ErrorServicio", Namespace="http://schemas.datacontract.org/2004/07/SGE.Service.Contracts.Faults")]
        LaFinanciera.ServicioPublicoOnline.ResultadoOperacion InformarCreditoOtorgado(string codigoFinanciera, int dni, string identificadorCredito, double montoOtorgado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ISTP1.Service.Contracts.Service/IServicioPublicoCredito/InformarCreditoOto" +
            "rgado", ReplyAction="http://ISTP1.Service.Contracts.Service/IServicioPublicoCredito/InformarCreditoOto" +
            "rgadoResponse")]
        System.Threading.Tasks.Task<LaFinanciera.ServicioPublicoOnline.ResultadoOperacion> InformarCreditoOtorgadoAsync(string codigoFinanciera, int dni, string identificadorCredito, double montoOtorgado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ISTP1.Service.Contracts.Service/IServicioPublicoCredito/InformarCreditoFin" +
            "alizado", ReplyAction="http://ISTP1.Service.Contracts.Service/IServicioPublicoCredito/InformarCreditoFin" +
            "alizadoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LaFinanciera.ServicioPublicoOnline.ErrorServicio), Action="http://ISTP1.Service.Contracts.Service/IServicioPublicoCredito/InformarCreditoFin" +
            "alizadoErrorServicioFault", Name="ErrorServicio", Namespace="http://schemas.datacontract.org/2004/07/SGE.Service.Contracts.Faults")]
        LaFinanciera.ServicioPublicoOnline.ResultadoOperacion InformarCreditoFinalizado(string codigoFinanciera, int dni, string identificadorCredito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ISTP1.Service.Contracts.Service/IServicioPublicoCredito/InformarCreditoFin" +
            "alizado", ReplyAction="http://ISTP1.Service.Contracts.Service/IServicioPublicoCredito/InformarCreditoFin" +
            "alizadoResponse")]
        System.Threading.Tasks.Task<LaFinanciera.ServicioPublicoOnline.ResultadoOperacion> InformarCreditoFinalizadoAsync(string codigoFinanciera, int dni, string identificadorCredito);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioPublicoCreditoChannel : LaFinanciera.ServicioPublicoOnline.IServicioPublicoCredito, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioPublicoCreditoClient : System.ServiceModel.ClientBase<LaFinanciera.ServicioPublicoOnline.IServicioPublicoCredito>, LaFinanciera.ServicioPublicoOnline.IServicioPublicoCredito {
        
        public ServicioPublicoCreditoClient() {
        }
        
        public ServicioPublicoCreditoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioPublicoCreditoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPublicoCreditoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPublicoCreditoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LaFinanciera.ServicioPublicoOnline.ResultadoEstadoCliente ObtenerEstadoCliente(string codigoFinanciera, int dni) {
            return base.Channel.ObtenerEstadoCliente(codigoFinanciera, dni);
        }
        
        public System.Threading.Tasks.Task<LaFinanciera.ServicioPublicoOnline.ResultadoEstadoCliente> ObtenerEstadoClienteAsync(string codigoFinanciera, int dni) {
            return base.Channel.ObtenerEstadoClienteAsync(codigoFinanciera, dni);
        }
        
        public LaFinanciera.ServicioPublicoOnline.ResultadoOperacion InformarCreditoOtorgado(string codigoFinanciera, int dni, string identificadorCredito, double montoOtorgado) {
            return base.Channel.InformarCreditoOtorgado(codigoFinanciera, dni, identificadorCredito, montoOtorgado);
        }
        
        public System.Threading.Tasks.Task<LaFinanciera.ServicioPublicoOnline.ResultadoOperacion> InformarCreditoOtorgadoAsync(string codigoFinanciera, int dni, string identificadorCredito, double montoOtorgado) {
            return base.Channel.InformarCreditoOtorgadoAsync(codigoFinanciera, dni, identificadorCredito, montoOtorgado);
        }
        
        public LaFinanciera.ServicioPublicoOnline.ResultadoOperacion InformarCreditoFinalizado(string codigoFinanciera, int dni, string identificadorCredito) {
            return base.Channel.InformarCreditoFinalizado(codigoFinanciera, dni, identificadorCredito);
        }
        
        public System.Threading.Tasks.Task<LaFinanciera.ServicioPublicoOnline.ResultadoOperacion> InformarCreditoFinalizadoAsync(string codigoFinanciera, int dni, string identificadorCredito) {
            return base.Channel.InformarCreditoFinalizadoAsync(codigoFinanciera, dni, identificadorCredito);
        }
    }
}
